apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: spring-boot-app-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=springboot'
    appkind: 'deployment'
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: spring-boot-chaos-sa
  experiments:
    - name: spring-boot-chaos
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '15'

            ## Period to wait before injection of chaos in sec
            - name: RAMP_TIME
              value: ''

            ## env var that describes the library used to execute the chaos
            ## default: litmus. Supported values: litmus
            - name: LIB
              value: 'litmus'
